spring:
  application:
    name: pong-service
  cloud:
    kubernetes:
      discovery:
        enabled: true
server:
  port: 8090

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"